import type { ThemeDefinition, ThemeLayer } from "@/theme-engine/types";

const ROOT = "/assets/color-cloud";

const colorCloudLayers: ThemeLayer[] = [
  {
    id: "background",
    asset: `${ROOT}/color-cloud-background.png`,
    zIndex: 0,
    opacity: 1,
    mobileOpacity: 1,
    fit: "cover",
  },
  {
    id: "glow-warm",
    asset: `${ROOT}/color-cloud-glow-warm.png`,
    zIndex: 1,
    opacity: 0.13,
    mobileOpacity: 0.1,
    animation: "cloud-glow",
    animationDuration: "68s",
    animationDelay: "-31s",
    animationX: "50px",
    animationY: "-42px",
    animationScale: "1.025",
    fit: "contain",
    position: { left: "-32%", bottom: "-38%" },
    size: { width: "116%", height: "116%" },
  },
  {
    id: "glow-cool",
    asset: `${ROOT}/color-cloud-glow-cool.png`,
    zIndex: 1,
    opacity: 0.13,
    mobileOpacity: 0.1,
    animation: "cloud-glow",
    animationDuration: "77s",
    animationDelay: "-68s",
    animationX: "-44px",
    animationY: "38px",
    animationScale: "1.028",
    fit: "contain",
    position: { right: "-34%", bottom: "-38%" },
    size: { width: "116%", height: "116%" },
  },
  {
    id: "glow-lavender",
    asset: `${ROOT}/color-cloud-glow-lavender.png`,
    zIndex: 1,
    opacity: 0.1,
    mobileOpacity: 0.08,
    animation: "cloud-glow",
    animationDuration: "61s",
    animationDelay: "-47s",
    animationX: "36px",
    animationY: "46px",
    animationScale: "1.025",
    fit: "contain",
    position: { top: "-35%", right: "-34%" },
    size: { width: "110%", height: "110%" },
  },
  {
    id: "cloud-peach",
    asset: `${ROOT}/color-cloud-peach.png`,
    zIndex: 3,
    opacity: 0.24,
    mobileOpacity: 0.18,
    animation: "cloud-drift",
    animationDuration: "26s",
    animationDelay: "-14s",
    animationX: "30px",
    animationY: "-18px",
    animationRotation: "1deg",
    animationScale: "1.03",
    fit: "contain",
    position: { top: "calc(-250px + 1vw)", left: "calc(-170px + 0.5vw)" },
    size: { width: "clamp(560px, 39.5vw, 800px)", height: "clamp(560px, 39.5vw, 800px)" },
  },
  {
    id: "cloud-lavender",
    asset: `${ROOT}/color-cloud-lavender.png`,
    zIndex: 3,
    opacity: 0.17,
    mobileOpacity: 0.14,
    animation: "cloud-drift",
    animationDuration: "31s",
    animationDelay: "-29s",
    animationX: "-26px",
    animationY: "16px",
    animationRotation: "-1.1deg",
    animationScale: "1.028",
    fit: "contain",
    position: { top: "calc(-35px + 1vw)", left: "calc(220px - 2vw)" },
    size: { width: "clamp(520px, 37.5vw, 760px)", height: "clamp(520px, 37.5vw, 760px)" },
  },
  {
    id: "cloud-mint",
    asset: `${ROOT}/color-cloud-mint.png`,
    zIndex: 3,
    opacity: 0.19,
    mobileOpacity: 0.16,
    animation: "cloud-drift",
    animationDuration: "23s",
    animationDelay: "-21s",
    animationX: "-32px",
    animationY: "-24px",
    animationRotation: "1.2deg",
    animationScale: "1.035",
    fit: "contain",
    position: { left: "calc(1040px + 0.5vw)", top: "calc(380px + 0.5vw)" },
    size: { width: "clamp(600px, 41.5vw, 840px)", height: "clamp(600px, 41.5vw, 840px)" },
  },
  {
    id: "cloud-pink",
    asset: `${ROOT}/color-cloud-pink.png`,
    zIndex: 3,
    opacity: 0.22,
    mobileOpacity: 0.18,
    animation: "cloud-drift",
    animationDuration: "28s",
    animationDelay: "-37s",
    animationX: "28px",
    animationY: "-20px",
    animationRotation: "-1deg",
    animationScale: "1.03",
    fit: "contain",
    position: { left: "calc(420px - 1.5vw)", top: "calc(170px - 1vw)" },
    size: { width: "clamp(600px, 44vw, 860px)", height: "clamp(600px, 44vw, 860px)" },
  },
  {
    id: "cloud-yellow",
    asset: `${ROOT}/color-cloud-yellow.png`,
    zIndex: 4,
    opacity: 0.18,
    mobileOpacity: 0.14,
    animation: "cloud-drift",
    animationDuration: "34s",
    animationDelay: "-8s",
    animationX: "-24px",
    animationY: "-18px",
    animationRotation: "0.9deg",
    animationScale: "1.025",
    fit: "contain",
    position: { left: "calc(820px - 0.5vw)", top: "calc(315px + 0.5vw)" },
    size: { width: "clamp(480px, 35vw, 720px)", height: "clamp(480px, 35vw, 720px)" },
  },
];

const colorCloudTheme: ThemeDefinition = {
  id: "classic",
  name: "Classic",
  description: "Светлая игровая среда с мягким пастельным движением",
  layers: colorCloudLayers,
  events: [],
  preview: { intensity: 0.88, events: false },
  player: { intensity: 1, events: true },
};

export default colorCloudTheme;
