/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TestPlayerRouteImport } from './routes/test-player'
import { Route as BuilderJeopardyRouteImport } from './routes/builder.jeopardy'
import { Route as BuilderMillionaireRouteImport } from './routes/builder.millionaire'
import { Route as BuilderQuizRouteImport } from './routes/builder.quiz'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as JeopardyGameIdResultsRouteImport } from './routes/jeopardy.$gameId.results'
import { Route as MillionaireGameIdResultsRouteImport } from './routes/millionaire.$gameId.results'
import { Route as PlayJeopardyIdRouteImport } from './routes/play.jeopardy.$id'
import { Route as PlayMillionaireIdRouteImport } from './routes/play.millionaire.$id'
import { Route as PlayQuizIdRouteImport } from './routes/play.quiz.$id'
import { Route as QuizGameIdResultsRouteImport } from './routes/quiz.$gameId.results'
import { Route as RoomCodeIndexRouteImport } from './routes/room.$code.index'
import { Route as RoomCodeAnswersRouteImport } from './routes/room.$code.answers'
import { Route as RoomCodePlayRouteImport } from './routes/room.$code.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPlayerRoute = TestPlayerRouteImport.update({
  id: '/test-player',
  path: '/test-player',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderJeopardyRoute = BuilderJeopardyRouteImport.update({
  id: '/builder/jeopardy',
  path: '/builder/jeopardy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderMillionaireRoute = BuilderMillionaireRouteImport.update({
  id: '/builder/millionaire',
  path: '/builder/millionaire',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderQuizRoute = BuilderQuizRouteImport.update({
  id: '/builder/quiz',
  path: '/builder/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JeopardyGameIdResultsRoute = JeopardyGameIdResultsRouteImport.update({
  id: '/jeopardy/$gameId/results',
  path: '/jeopardy/$gameId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const MillionaireGameIdResultsRoute =
  MillionaireGameIdResultsRouteImport.update({
    id: '/millionaire/$gameId/results',
    path: '/millionaire/$gameId/results',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayJeopardyIdRoute = PlayJeopardyIdRouteImport.update({
  id: '/play/jeopardy/$id',
  path: '/play/jeopardy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMillionaireIdRoute = PlayMillionaireIdRouteImport.update({
  id: '/play/millionaire/$id',
  path: '/play/millionaire/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizIdRoute = PlayQuizIdRouteImport.update({
  id: '/play/quiz/$id',
  path: '/play/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGameIdResultsRoute = QuizGameIdResultsRouteImport.update({
  id: '/quiz/$gameId/results',
  path: '/quiz/$gameId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeIndexRoute = RoomCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomCodeRoute,
} as any)
const RoomCodeAnswersRoute = RoomCodeAnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => RoomCodeRoute,
} as any)
const RoomCodePlayRoute = RoomCodePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => RoomCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/test-player': typeof TestPlayerRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/room/$code': typeof RoomCodeRouteWithChildren
  '/profile/': typeof ProfileIndexRoute
  '/jeopardy/$gameId/results': typeof JeopardyGameIdResultsRoute
  '/millionaire/$gameId/results': typeof MillionaireGameIdResultsRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
  '/room/$code/answers': typeof RoomCodeAnswersRoute
  '/room/$code/play': typeof RoomCodePlayRoute
  '/room/$code/': typeof RoomCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/test-player': typeof TestPlayerRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile': typeof ProfileIndexRoute
  '/jeopardy/$gameId/results': typeof JeopardyGameIdResultsRoute
  '/millionaire/$gameId/results': typeof MillionaireGameIdResultsRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
  '/room/$code/answers': typeof RoomCodeAnswersRoute
  '/room/$code/play': typeof RoomCodePlayRoute
  '/room/$code': typeof RoomCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/test-player': typeof TestPlayerRoute
  '/builder/jeopardy': typeof BuilderJeopardyRoute
  '/builder/millionaire': typeof BuilderMillionaireRoute
  '/builder/quiz': typeof BuilderQuizRoute
  '/game/$id': typeof GameIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/room/$code': typeof RoomCodeRouteWithChildren
  '/profile/': typeof ProfileIndexRoute
  '/jeopardy/$gameId/results': typeof JeopardyGameIdResultsRoute
  '/millionaire/$gameId/results': typeof MillionaireGameIdResultsRoute
  '/play/jeopardy/$id': typeof PlayJeopardyIdRoute
  '/play/millionaire/$id': typeof PlayMillionaireIdRoute
  '/play/quiz/$id': typeof PlayQuizIdRoute
  '/quiz/$gameId/results': typeof QuizGameIdResultsRoute
  '/room/$code/answers': typeof RoomCodeAnswersRoute
  '/room/$code/play': typeof RoomCodePlayRoute
  '/room/$code/': typeof RoomCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/join'
    | '/library'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/test-player'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/game/$id'
    | '/profile/$userId'
    | '/room/$code'
    | '/profile/'
    | '/jeopardy/$gameId/results'
    | '/millionaire/$gameId/results'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
    | '/room/$code/answers'
    | '/room/$code/play'
    | '/room/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/join'
    | '/library'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/test-player'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/game/$id'
    | '/profile/$userId'
    | '/profile'
    | '/jeopardy/$gameId/results'
    | '/millionaire/$gameId/results'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
    | '/room/$code/answers'
    | '/room/$code/play'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/join'
    | '/library'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/test-player'
    | '/builder/jeopardy'
    | '/builder/millionaire'
    | '/builder/quiz'
    | '/game/$id'
    | '/profile/$userId'
    | '/room/$code'
    | '/profile/'
    | '/jeopardy/$gameId/results'
    | '/millionaire/$gameId/results'
    | '/play/jeopardy/$id'
    | '/play/millionaire/$id'
    | '/play/quiz/$id'
    | '/quiz/$gameId/results'
    | '/room/$code/answers'
    | '/room/$code/play'
    | '/room/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TestPlayerRoute: typeof TestPlayerRoute
  BuilderJeopardyRoute: typeof BuilderJeopardyRoute
  BuilderMillionaireRoute: typeof BuilderMillionaireRoute
  BuilderQuizRoute: typeof BuilderQuizRoute
  GameIdRoute: typeof GameIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  RoomCodeRoute: typeof RoomCodeRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
  JeopardyGameIdResultsRoute: typeof JeopardyGameIdResultsRoute
  MillionaireGameIdResultsRoute: typeof MillionaireGameIdResultsRoute
  PlayJeopardyIdRoute: typeof PlayJeopardyIdRoute
  PlayMillionaireIdRoute: typeof PlayMillionaireIdRoute
  PlayQuizIdRoute: typeof PlayQuizIdRoute
  QuizGameIdResultsRoute: typeof QuizGameIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-player': {
      id: '/test-player'
      path: '/test-player'
      fullPath: '/test-player'
      preLoaderRoute: typeof TestPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/jeopardy': {
      id: '/builder/jeopardy'
      path: '/builder/jeopardy'
      fullPath: '/builder/jeopardy'
      preLoaderRoute: typeof BuilderJeopardyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/millionaire': {
      id: '/builder/millionaire'
      path: '/builder/millionaire'
      fullPath: '/builder/millionaire'
      preLoaderRoute: typeof BuilderMillionaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/quiz': {
      id: '/builder/quiz'
      path: '/builder/quiz'
      fullPath: '/builder/quiz'
      preLoaderRoute: typeof BuilderQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeopardy/$gameId/results': {
      id: '/jeopardy/$gameId/results'
      path: '/jeopardy/$gameId/results'
      fullPath: '/jeopardy/$gameId/results'
      preLoaderRoute: typeof JeopardyGameIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/millionaire/$gameId/results': {
      id: '/millionaire/$gameId/results'
      path: '/millionaire/$gameId/results'
      fullPath: '/millionaire/$gameId/results'
      preLoaderRoute: typeof MillionaireGameIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/jeopardy/$id': {
      id: '/play/jeopardy/$id'
      path: '/play/jeopardy/$id'
      fullPath: '/play/jeopardy/$id'
      preLoaderRoute: typeof PlayJeopardyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/millionaire/$id': {
      id: '/play/millionaire/$id'
      path: '/play/millionaire/$id'
      fullPath: '/play/millionaire/$id'
      preLoaderRoute: typeof PlayMillionaireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/quiz/$id': {
      id: '/play/quiz/$id'
      path: '/play/quiz/$id'
      fullPath: '/play/quiz/$id'
      preLoaderRoute: typeof PlayQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$gameId/results': {
      id: '/quiz/$gameId/results'
      path: '/quiz/$gameId/results'
      fullPath: '/quiz/$gameId/results'
      preLoaderRoute: typeof QuizGameIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code/': {
      id: '/room/$code/'
      path: '/'
      fullPath: '/room/$code/'
      preLoaderRoute: typeof RoomCodeIndexRouteImport
      parentRoute: typeof RoomCodeRoute
    }
    '/room/$code/answers': {
      id: '/room/$code/answers'
      path: '/answers'
      fullPath: '/room/$code/answers'
      preLoaderRoute: typeof RoomCodeAnswersRouteImport
      parentRoute: typeof RoomCodeRoute
    }
    '/room/$code/play': {
      id: '/room/$code/play'
      path: '/play'
      fullPath: '/room/$code/play'
      preLoaderRoute: typeof RoomCodePlayRouteImport
      parentRoute: typeof RoomCodeRoute
    }
  }
}

interface RoomCodeRouteChildren {
  RoomCodeAnswersRoute: typeof RoomCodeAnswersRoute
  RoomCodePlayRoute: typeof RoomCodePlayRoute
  RoomCodeIndexRoute: typeof RoomCodeIndexRoute
}

const RoomCodeRouteChildren: RoomCodeRouteChildren = {
  RoomCodeAnswersRoute: RoomCodeAnswersRoute,
  RoomCodePlayRoute: RoomCodePlayRoute,
  RoomCodeIndexRoute: RoomCodeIndexRoute,
}

const RoomCodeRouteWithChildren = RoomCodeRoute._addFileChildren(
  RoomCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TestPlayerRoute: TestPlayerRoute,
  BuilderJeopardyRoute: BuilderJeopardyRoute,
  BuilderMillionaireRoute: BuilderMillionaireRoute,
  BuilderQuizRoute: BuilderQuizRoute,
  GameIdRoute: GameIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  RoomCodeRoute: RoomCodeRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
  JeopardyGameIdResultsRoute: JeopardyGameIdResultsRoute,
  MillionaireGameIdResultsRoute: MillionaireGameIdResultsRoute,
  PlayJeopardyIdRoute: PlayJeopardyIdRoute,
  PlayMillionaireIdRoute: PlayMillionaireIdRoute,
  PlayQuizIdRoute: PlayQuizIdRoute,
  QuizGameIdResultsRoute: QuizGameIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
