import type { ThemeDefinition, ThemeLayer } from "@/theme-engine/types";

const ROOT = "/assets/night-sky";

const manualEvents = [
  {
    id: "shooting-star" as const,
    durationMs: 3600,
    minDelayMs: 24000,
    maxDelayMs: 46000,
    mobile: true,
  },
  {
    id: "satellite" as const,
    durationMs: 5200,
    minDelayMs: 42000,
    maxDelayMs: 72000,
    mobile: false,
  },
  {
    id: "aurora-pulse" as const,
    durationMs: 4200,
    minDelayMs: 30000,
    maxDelayMs: 60000,
    mobile: true,
  },
  {
    id: "moon-glow-boost" as const,
    durationMs: 3000,
    minDelayMs: 36000,
    maxDelayMs: 68000,
    mobile: true,
  },
];

const grassPlacements = [
  ["01", "0%", "19%", "43%", "-2.4s", "3.2deg", "6.8s"],
  ["02", "5%", "16%", "36%", "-5.8s", "5.4deg", "8.7s"],
  ["03", "12%", "22%", "48%", "-1.1s", "4.1deg", "10.4s"],
  ["04", "19%", "17%", "40%", "-7.2s", "6.7deg", "7.9s"],
  ["05", "27%", "14%", "31%", "-3.7s", "3.8deg", "12.6s"],
  ["06", "34%", "21%", "45%", "-8.6s", "5.9deg", "9.3s"],
  ["07", "42%", "18%", "38%", "-4.9s", "4.6deg", "14.2s"],
  ["08", "49%", "15%", "35%", "-2.8s", "7.4deg", "11.1s"],
  ["09", "56%", "23%", "50%", "-6.5s", "3.5deg", "7.4s"],
  ["10", "64%", "18%", "42%", "-1.8s", "6.2deg", "13.5s"],
  ["11", "71%", "15%", "34%", "-7.8s", "4.3deg", "9.8s"],
  ["12", "77%", "20%", "46%", "-5.1s", "7.8deg", "15.4s"],
  ["13", "84%", "16%", "37%", "-3.2s", "3.9deg", "8.3s"],
  ["14", "90%", "22%", "49%", "-8.1s", "5.1deg", "12.1s"],
  ["15", "96%", "18%", "41%", "-4.2s", "6.9deg", "10.8s"],
] as const;

function createGrassLayers(): ThemeLayer[] {
  return grassPlacements.map(
    ([number, left, width, height, delay, amplitude, duration], index) => ({
      id: `grass-${number}`,
      asset: `${ROOT}/layers/grass-${number}.webp`,
      zIndex: 12,
      opacity: 0.66 + (index % 4) * 0.05,
      mobileOpacity: 0.5 + (index % 3) * 0.05,
      animation: "grass-sway",
      animationDuration: duration,
      animationDelay: delay,
      animationAmplitude: amplitude,
      fit: "contain",
      position: { top: "auto", right: "auto", bottom: "-2%", left },
      size: { width, height },
      objectPosition: "bottom center",
    }),
  );
}

const nightSkyTheme: ThemeDefinition = {
  id: "midnight",
  name: "Night Sky",
  description: "Тихий ночной мир с луной, туманом и далёкими звёздами",
  layers: [
    {
      id: "background",
      asset: `${ROOT}/layers/background.webp`,
      zIndex: 0,
      opacity: 1,
      mobileOpacity: 1,
      fit: "cover",
    },
    {
      id: "tiny-stars",
      asset: `${ROOT}/vectors/tiny-stars.svg`,
      kind: "star-field",
      zIndex: 6,
      opacity: 0.464,
      mobileOpacity: 0.344,
      animation: "none",
      starCount: 32,
      fit: "cover",
    },
    {
      id: "medium-stars",
      asset: `${ROOT}/vectors/medium-stars.svg`,
      kind: "star-field",
      zIndex: 6,
      opacity: 0.464,
      mobileOpacity: 0.36,
      animation: "none",
      starCount: 28,
      fit: "cover",
    },
    {
      id: "nebula",
      asset: `${ROOT}/layers/nebula.webp`,
      zIndex: 4,
      opacity: 0.2048,
      mobileOpacity: 0.1584,
      blendMode: "screen",
      animation: "nebula-breathe",
      animationDuration: "151.56s",
      animationDelay: "-48.44s",
      fit: "cover",
    },
    {
      id: "nebula-density",
      asset: `${ROOT}/layers/nebula.webp`,
      zIndex: 4,
      opacity: 0.072,
      mobileOpacity: 0.0512,
      blendMode: "screen",
      animation: "nebula-density",
      animationDuration: "204.69s",
      animationDelay: "-73.44s",
      fit: "cover",
      position: { top: "-3%", left: "-5%" },
      size: { width: "110%", height: "110%" },
    },
    {
      id: "aurora",
      asset: `${ROOT}/layers/aurora.webp`,
      zIndex: 5,
      opacity: 0.1536,
      mobileOpacity: 0.1088,
      blendMode: "screen",
      animation: "aurora-flow",
      animationDuration: "60.94s",
      animationDelay: "-26.56s",
      fit: "cover",
    },
    {
      id: "aurora-depth",
      asset: `${ROOT}/layers/aurora.webp`,
      zIndex: 5,
      opacity: 0.064,
      mobileOpacity: 0.0448,
      blendMode: "screen",
      animation: "aurora-depth",
      animationDuration: "176.56s",
      animationDelay: "-67.19s",
      fit: "cover",
      position: { top: "-1%", left: "-2%" },
      size: { width: "104%", height: "105%" },
    },
    {
      id: "bright-stars",
      asset: `${ROOT}/vectors/bright-stars.svg`,
      kind: "star-field",
      zIndex: 6,
      opacity: 0.464,
      mobileOpacity: 0.344,
      animation: "none",
      starCount: 8,
      fit: "cover",
    },
    {
      id: "moon",
      asset: `${ROOT}/layers/moon.webp`,
      zIndex: 8,
      opacity: 0.94,
      mobileOpacity: 0.78,
      animation: "float",
      animationDuration: "18s",
      animationDelay: "-7s",
      fit: "contain",
      position: { top: "-1vh", right: "5vw" },
      size: { width: "min(45vh, 26rem)", height: "min(45vh, 26rem)" },
    },
    {
      id: "mountains",
      asset: `${ROOT}/layers/mountains.webp`,
      zIndex: 9,
      opacity: 0.94,
      mobileOpacity: 0.82,
      animation: "drift",
      animationDuration: "51s",
      animationDelay: "-21s",
      fit: "cover",
    },
    {
      id: "water-glow",
      asset: `${ROOT}/layers/water-glow.webp`,
      zIndex: 10,
      opacity: 0.5,
      mobileOpacity: 0.32,
      blendMode: "screen",
      animation: "water-ripple",
      animationDuration: "23s",
      animationDelay: "-10s",
      fit: "cover",
    },
    {
      id: "water-shimmer",
      asset: `${ROOT}/layers/water-glow.webp`,
      zIndex: 10,
      opacity: 0.2,
      mobileOpacity: 0.14,
      blendMode: "screen",
      animation: "water-shimmer",
      animationDuration: "14s",
      animationDelay: "-3s",
      fit: "cover",
      position: { left: "-2%", bottom: "-1%" },
      size: { width: "104%", height: "104%" },
    },
    {
      id: "fog-back",
      asset: `${ROOT}/layers/fog.webp`,
      zIndex: 11,
      opacity: 0.184,
      mobileOpacity: 0.12,
      blendMode: "screen",
      animation: "mist-far",
      animationDuration: "67.19s",
      animationDelay: "-20.31s",
      fit: "cover",
      position: { top: "auto", bottom: "-5%" },
      size: { height: "64%" },
      objectPosition: "bottom",
    },
    {
      id: "fog-front",
      asset: `${ROOT}/layers/fog.webp`,
      zIndex: 11,
      opacity: 0.16,
      mobileOpacity: 0.104,
      blendMode: "screen",
      animation: "mist-near",
      animationDuration: "45.31s",
      animationDelay: "-12.5s",
      fit: "cover",
      position: { top: "auto", left: "-4%", bottom: "-11%" },
      size: { width: "108%", height: "55%" },
      objectPosition: "bottom",
    },
    {
      id: "air-haze",
      asset: `${ROOT}/layers/fog.webp`,
      zIndex: 11,
      opacity: 0.056,
      mobileOpacity: 0.032,
      blendMode: "screen",
      animation: "mist-haze",
      animationDuration: "73.44s",
      animationDelay: "-34.38s",
      fit: "cover",
      position: { top: "auto", left: "-6%", bottom: "-6%" },
      size: { width: "112%", height: "46%" },
      objectPosition: "bottom",
    },
    ...createGrassLayers(),
  ],
  events: [],
  manualEvents,
  preview: { intensity: 0.72, events: false },
  player: { intensity: 1, events: true },
};

export default nightSkyTheme;
